import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";
import "./globals.css";
import { ThemeWrapper } from "./components/ThemeProvider/ThemeProvider";
import AuthLayout from "./components/Layouts/AuthLayout";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthLayout>
      <html lang="en">
        <ThemeWrapper>
          <body className={`${inter.className} min-h-screen`}>{children}</body>
        </ThemeWrapper>
      </html>
    </AuthLayout>
  );
}
